#cloud-config

coreos:
  etcd:
    discovery: https://discovery.etcd.io/a9d341f0e1fb9f77df580ffaa7c0283b
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  fleet:
    public-ip: $private_ipv4   # used for fleetctl ssh command
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
